export const APP_ERROR_CODES = [
  "AUTH_UNAUTHORIZED",
  "AUTH_FORBIDDEN",
  "AUTH_EXPIRED",
  "AUTH_PROVIDER_ERROR",
  "AUTH_PROVIDER_DENIED",
  "NETWORK_OFFLINE",
  "NETWORK_TIMEOUT",
  "NETWORK_FAILED",
  "API_BAD_REQUEST",
  "API_VALIDATION",
  "API_CONFLICT",
  "API_PRECONDITION_FAILED",
  "API_NOT_FOUND",
  "API_RATE_LIMIT",
  "API_SERVER",
  "API_UNAVAILABLE",
  "UNKNOWN",
] as const;

export type AppErrorCode = (typeof APP_ERROR_CODES)[number];
