/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LevelUpRouteImport } from './routes/level-up'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChestRouteImport } from './routes/chest'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelUpRoute = LevelUpRouteImport.update({
  id: '/level-up',
  path: '/level-up',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChestRoute = ChestRouteImport.update({
  id: '/chest',
  path: '/chest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chest': typeof ChestRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/level-up': typeof LevelUpRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/onboarding': typeof OnboardingRoute
  '/ranking': typeof RankingRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chest': typeof ChestRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/level-up': typeof LevelUpRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/onboarding': typeof OnboardingRoute
  '/ranking': typeof RankingRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chest': typeof ChestRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/level-up': typeof LevelUpRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/onboarding': typeof OnboardingRoute
  '/ranking': typeof RankingRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chest'
    | '/dashboard'
    | '/inventory'
    | '/level-up'
    | '/login'
    | '/logs'
    | '/onboarding'
    | '/ranking'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chest'
    | '/dashboard'
    | '/inventory'
    | '/level-up'
    | '/login'
    | '/logs'
    | '/onboarding'
    | '/ranking'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/chest'
    | '/dashboard'
    | '/inventory'
    | '/level-up'
    | '/login'
    | '/logs'
    | '/onboarding'
    | '/ranking'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChestRoute: typeof ChestRoute
  DashboardRoute: typeof DashboardRoute
  InventoryRoute: typeof InventoryRoute
  LevelUpRoute: typeof LevelUpRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  OnboardingRoute: typeof OnboardingRoute
  RankingRoute: typeof RankingRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/level-up': {
      id: '/level-up'
      path: '/level-up'
      fullPath: '/level-up'
      preLoaderRoute: typeof LevelUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chest': {
      id: '/chest'
      path: '/chest'
      fullPath: '/chest'
      preLoaderRoute: typeof ChestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChestRoute: ChestRoute,
  DashboardRoute: DashboardRoute,
  InventoryRoute: InventoryRoute,
  LevelUpRoute: LevelUpRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  OnboardingRoute: OnboardingRoute,
  RankingRoute: RankingRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
